"""add ai fields to user_settings

Revision ID: 05cf371ae230
Revises: 089fe16d3062
Create Date: 2026-03-25 06:58:07.877643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05cf371ae230'
down_revision = '089fe16d3062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ollama_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ollama_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('claude_model', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('claude_model')
        batch_op.drop_column('ollama_model')
        batch_op.drop_column('ollama_url')
        batch_op.drop_column('ai_provider')

    # ### end Alembic commands ###
