"""add user_settings table

Revision ID: 089fe16d3062
Revises: 4192ade72033
Create Date: 2026-03-25 06:47:27.706291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089fe16d3062'
down_revision = '4192ade72033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('icloud_username', sa.String(length=255), nullable=True),
    sa.Column('icloud_app_password', sa.String(length=255), nullable=True),
    sa.Column('claude_api_key', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
