"""add closed_at to issues

Revision ID: 2e23f66a6c28
Revises: ebbe4ed05be4
Create Date: 2026-03-25 11:16:26.641792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e23f66a6c28'
down_revision = 'ebbe4ed05be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('closed_at')

    # ### end Alembic commands ###
