"""ki_agents_and_runs

Revision ID: 3a9c3733b32c
Revises: 7f905107f764
Create Date: 2026-03-26 11:32:41.887904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9c3733b32c'
down_revision = '7f905107f764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ki_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('api_provider', sa.String(length=20), nullable=True),
    sa.Column('api_model', sa.String(length=100), nullable=True),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=True),
    sa.Column('interval_min', sa.Integer(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('workspace', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=True),
    sa.Column('notify_telegram', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ki_agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['ki_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ki_agent_runs')
    op.drop_table('ki_agents')
    # ### end Alembic commands ###
