"""add is_admin to users

Revision ID: 503cba6f33f6
Revises: 68a9a72f5800
Create Date: 2026-03-23 14:11:27.929719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503cba6f33f6'
down_revision = '68a9a72f5800'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # Alle bestehenden Nutzer zu Admins machen
    op.execute("UPDATE users SET is_admin = 1")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
